### ISSUE TITLE
Layout breaks for screen-size > 576px

### ISSUE THREAD

**Issue by DemonDaddy22** [garimasingh128/Hacktoberfest2020-MovieDo#243]
**Describe the bug**
For small screen sizes (particularly mobiles), responsiveness works fine, but for screens of greater sizes, the view breaks into a grid of 3 columns which doesn't look good.

**To Reproduce**
1. Open up inspect/console
2. Reduce the screen size and check the responsiveness for smaller screen sizes

**Expected behavior**
For screen sizes (like tabs), the grid should contain 2 columns, and for greater sizes, it should expand to 3 columns.

**Screenshots**
<img width="561" alt="Screenshot 2020-10-05 at 8 22 43 PM" src="https://user-images.githubusercontent.com/39908472/95095825-2a61ed80-0749-11eb-86e8-5b38919c9ee9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**
Assign me this issue and I'll fix it.

**Comment by DCox2016** [comment]
Can I give this a go?

**Comment by DCox2016** [comment]
![Screen Shot 2020-10-09 at 4 50 54 PM](https://user-images.githubusercontent.com/17097992/95631204-47e8cd00-0a51-11eb-8baf-1990e03344eb.png)
![Screen Shot 2020-10-09 at 4 51 09 PM](https://user-images.githubusercontent.com/17097992/95631208-49b29080-0a51-11eb-999a-d9f596118637.png)
![Screen Shot 2020-10-09 at 4 51 23 PM](https://user-images.githubusercontent.com/17097992/95631213-4c14ea80-0a51-11eb-97b8-9543a51e9a7e.png)
![Screen Shot 2020-10-09 at 4 51 47 PM](https://user-images.githubusercontent.com/17097992/95631215-4d461780-0a51-11eb-86a5-a83354a609d5.png)
I fixed the small screen issue. I made some style changes and will upload the code soon. Ran into a small git issue I need to fix
